on: [push, pull_request]
jobs:
  emulator_test:
    name: Run all tests using Firebase Emulators Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Firebase Emulator Suite
        run: npm install -g firebase-tools
      - name: Install dependencies
        run: npm install
      - name: Start the Firebase Emulators
        run: firebase emulators:start &
      - name: Run tests with npm
        working-directory: test
        run: npm test
      - name: Run tests with npx mocha
        working-directory: test
        run: npx mocha
