on: [push, pull_request]
jobs:
  emulator_test:
    name: Run all tests using Firebase Emulators Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Firebase Emulator Suite
        run: npm install -g firebase-tools
      - name: Install dependencies
        run: npm install
      - name: Install mocha
        working-directory: test
        run: npm install mocha
      - name: Run tests with npm
        working-directory: test
        run: npm test
